# SPDX-License-Identifier: MIT
---
- name: Create a new set of keys and fetch them
  hosts: nbde_servers_test
  become: true


  roles:
    - role: nbde_server
      nbde_server_fetch_keys: yes
      nbde_server_keys_dir: "my-keys"

# vim:set ts=2 sw=2 et:
