# SPDX-License-Identifier: MIT
---
- name: Ensure there are keys and they are deployed to every server
  hosts: nbde_servers_test
  become: true


  roles:
    - role: nbde_server
      nbde_server_deploy_keys: yes
      nbde_server_keys_dir: "keys-to-deploy"

# vim:set ts=2 sw=2 et:
